services:
  api:
    image: ghcr.io/tftiwnbe/grindboard:latest
    container_name: grindboard
    restart: unless-stopped

    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ../data:/app/data
    working_dir: /app
